### ISSUE TITLE
license.txt doesn't contain the license text

### ISSUE THREAD

**Issue by tgodau** [SiliconLabs/uC-OS2#2]
Hi,

license.txt seems to be just some kind of license header, where you claim, that the source code is under Apache-2.0, but not the license itself. The Apache-2.0 license requires in 4(a):
"You must give any other recipients of the Work or Derivative Works a copy of this License; and" ...

But there is no copy of the license.

I would suggest to concatenate the text from https://www.apache.org/licenses/LICENSE-2.0.txt at the bottom of "license.txt" (just a link is not sufficient!) to comply to the license.

**This should be necessary for all "uC-..." repositories.**

This would help all the users of the source code at license scanning and to become license compliant.

Thank you.

Regards, Thorsten

**Comment by forg0ne** [comment]
Hello Thorsten,

Thank you for notifying us.
We apologize for the omission, and will work on getting all the repositories updated with the license text.

Regards,
Sharbel

**Comment by forg0ne** [comment]
Hello Thorsten,

The uC repos should now be compliant.
Please let us know if you have any issues with the changes.

Regards,
Sharbel

**Comment by tgodau** [comment]
Hi Sharbel,

great stuff :-)
Thank you very much for your fast response and the efforts.

Regards, Thorsten
