### ISSUE TITLE
Port Required for ARMv8

### ISSUE THREAD

**Issue by vamsireddybtech** [SiliconLabs/uC-OS2#5]
Can any one Knows, how to port to Cortex-M23 Controller. OS-2 Port is missing for the Same.

**Comment by vamsireddybtech** [comment]
Solved the Problem,

**Comment by hiepbk94** [comment]
Dear my friend @vamsireddybtech,
I have the same question, how to port to cortex-m23? Please share with me your solution.
Thank you very much.
